#pragma config(Sensor, S1,     leftLight,      sensorLightActive)
#pragma config(Sensor, S3,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     rightLight,     sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int lightThresh = 50;                               //threshold for difference between black and white
	int corners = 0;                                    //corners to turn around on
while(corners < 4){
	while(SensorValue(leftLight)>lightThresh){          //line following
		if(SensorValue(rightLight)>lightThresh){
			motor[motorB]=50;
			motor[motorC]=0;
		}
		if(SensorValue(rightLight)<lightThresh){
			motor[motorC]=50;
			motor[motorB]=0;
		}
	}
	corners += 1;
	motor[motorB]=30;                                    //pushing trash part
	motor[motorC]=30;
	wait1Msec(500);
	motor[motorB]=-30;
	motor[motorC]=-30;
	wait1Msec(500);
	nMotorEncoder[motorB] = 0;
	while(nMotorEncoder[motorB]>-180){                   //trying to turn left 90 degrees
		motor[motorB]=-25;
		motor[motorC]=25;
	}
}
}
