#pragma config(Sensor, S1,     upLight,        sensorLightActive)
#pragma config(Sensor, S2,     leftLight,      sensorEV3_Color)
#pragma config(Sensor, S4,     rightLight,     sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void resetEncoder(){
	/* reset motor encoder */
	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;
}
float measuredist(){
	/*Floaty tings */
	float circum = 5.6 * 3.14159265;
	float degdist = circum/360;
	float distance = degdist*(nMotorEncoder[motorB]);
	return distance;
}
float measuredistC(){
	float circum = 5.6 * 3.14159265;
	float degdist = circum/360;
	float distance = degdist*(nMotorEncoder[motorC]);
	return distance;
}
float averagedist(){
	float c = measuredistC();
	float b = measuredist();
	return ((b+c)/2);
}
void linefollowccw(int lightThresh){
	if(SensorValue(rightLight)>lightThresh){
			motor[motorB]=50;
			motor[motorC]=0;
		}
	if(SensorValue(rightLight)<lightThresh){
		motor[motorC]=50;
		motor[motorB]=0;
	}
}
void linefollowcw(int lightThresh){
	if(SensorValue(rightLight)>lightThresh){
			motor[motorB]=0;
			motor[motorC]=50;
		}
	if(SensorValue(rightLight)<lightThresh){
		motor[motorC]=0;
		motor[motorB]=50;
	} 
}
task main(){
	int lightThresh = 40;
	float distance = 50.0; //distance to travel while line following
	resetEncoder();
	float x = 0.0;
	while(x<distance){
		linefollowccw(lightThresh);
		x = measuredist();
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(1000);
	resetEncoder();
	x = 0.0
	while(x<distance){
		linefollowccw(lightThresh);
		x = averagedist();
	}
}