#pragma config(Sensor, S2,     Light,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	if(SensorValue(Light)>50){
		motor[motorB]=50;
		motor[motorC]=0;
	}
	if(SensorValue(Light)<50){
		motor[motorC]=50;
		motor[motorB]=0;
	}
}
}
