#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     Light,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int black = 0;
	int white = 0;
	int niki = 0;
	while(SensorValue(Touch)==0){

	}
	black = SensorValue(Touch);
	wait1Msec(1000);
	while(SensorValue(Touch)==0){

	}
	white = SensorValue(Touch);
	niki = (black + white)/2;
	while(true){
		if(SensorValue(Light)>niki){
			motor[motorB]=50;
			motor[motorC]=0;
		}
		if(SensorValue(Light)<niki){
			motor[motorC]=50;
			motor[motorB]=0;
		}
	}
}
