#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     Light,          sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int n = 3;

 while(n > 0) {

	while(SensorValue(Touch)==0){
		motor[motorB] = 50;
		motor[motorC] = 50;
	}

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(1000);
	n--;

}
/*
while(SensorValue(Light)>50) {
	motor[motorB]=50;
	motor[motorC]=50;

}
*/
}
