#pragma config(Sensor, S3,     ultrasonic,     sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true) {
	int sonic = SensorValue(ultrasonic);
displayTextLine(3,"Distance: %d", sonic);
wait1Msec(200);
}


}
